In [1]:
import os
os.chdir('/home/cjtu/projects/essi21/essi21')
import mixing as mm
import pandas as pd
import numpy as np

f_ice = '/home/cjtu/projects/essi21/data/210702/essi00000/ice_columns_essi00000.csv'
df_ice = pd.read_csv(f_ice)
df_ice.head()

df = mm.read_crater_list()  # DataFrame, len: NC
ej_thickness_time = mm.get_ejecta_thickness_matrix(df)  # [m] shape: NY,NX,NT
ej_cols = pd.DataFrame(ej_thickness_time, columns=df.cname)

In [2]:
ej_cols.columns

Index(['Haworth', 'Shoemaker', 'Faustini', 'Amundsen', 'Cabeus', 'Cabeus B',
       'de Gerlache', 'Hedervari', 'Idel'son L', 'Unnamed 1', 'Nobile',
       'Scott', 'Scott E', 'Slater', 'Sverdrup', 'Wiechert P', 'Unnamed 2',
       'Wiechert', 'Idel'son', 'Unnamed 3', 'Wiechert U', 'Wiechert J',
       'Shackleton', 'Amundsen C'],
      dtype='object', name='cname')

In [3]:
coldtrap = 'Haworth'

def get_strat_col(ice_df, ej_df, coldtrap='Haworth'):
    strat_col = df_ice[['time']].copy()
    strat_col['ice'] = df_ice.loc[:, coldtrap].values
    strat_col['ejecta'] = ej_cols.loc[:, coldtrap].values
    strat_col.insert(1, 'depth', 0)
    strat_col.insert(2, 'label', '')

    for i, row in strat_col.iterrows():
        strat_col.loc[i+1, 'depth'] = strat_col.loc[i, 'depth'] + row.ice + row.ejecta
        if row.ejecta:
            ej_row = ej_cols.iloc[i]
            try:
                label = ej_row[ej_row == ej_row.min()].keys()[0]
            except Exception as e:
                print(e)
        elif row.ice:
            label = 'Ice'
        else:
            label = 'void'
        strat_col.loc[i, 'label'] = label
    strat_col = strat_col.drop(len(strat_col)-1)
    strat_col['depth'] = strat_col.depth.max() - strat_col.depth
    return strat_col[strat_col.label != 'void']
strat = get_strat_col(df_ice, ej_cols, coldtrap)
strat.tail()

             time     depth     label       ice    ejecta
105  3.200000e+09  5.178307  Wiechert  0.000000  0.404449
112  3.130000e+09  4.773858       Ice  0.191311  0.000000
122  3.030000e+09  4.582547       Ice  2.826662  0.000000
245  1.800000e+09  1.755885  Amundsen  0.000000  0.179705
383  4.200000e+08  1.576180       Ice  1.576180  0.000000

In [9]:
strat[['label', 'depth']][:20:-1]

         label       depth
383        Ice    1.576180
245   Amundsen    1.755885
122        Ice    4.582547
112        Ice    4.773858
105   Wiechert    5.178307
86         Ice    5.195146
85   Unnamed 3    8.342381
75    Amundsen    8.493634
71         Ice    8.672246
59         Ice    8.771650
58         Ice    9.042210
57         Ice    9.437358
55   Unnamed 2   11.029752
54         Ice   11.036825
51         Ice   11.135113
50         Ice   11.140475
48         Ice   11.501175
47         Ice   14.122285
46         Ice   14.360165
45    Amundsen   25.219326
43         Ice   27.718891
42         Ice   29.827392
41         Ice   42.554949
40         Ice   43.681241
39         Ice   49.782664
38         Ice   52.851473
37         Ice   53.718929
36         Ice   60.686323
35   Unnamed 2   72.691815
34         Ice   81.443493
33         Ice   99.875506
32         Ice  103.989370
31         Ice  105.286401
30         Ice  114.073773
29         Ice  119.343175
28         Ice  124.629767
27         Ice  138.731990
26         Ice  146.689124
25         Ice  152.774205
24         Ice  175.870789
23         Ice  201.058531
22         Ice  212.531403
21         Ice  224.476756

In [12]:
strat[strat['label'] == 'Wiechert']

             time     depth     label  ice    ejecta
105  3.200000e+09  5.178307  Wiechert  0.0  0.404449

In [14]:
strat[strat['depth'] > 350]

            time       depth      label        ice    ejecta
0   4.250000e+09  984.267287        Ice  66.545370  0.000000
1   4.240000e+09  917.721917        Ice  50.207860  0.000000
2   4.230000e+09  867.514057        Ice  32.878820  0.000000
3   4.220000e+09  834.635237        Ice  47.892840  0.000000
4   4.210000e+09  786.742397        Ice  21.232365  0.000000
5   4.200000e+09  765.510032        Ice  44.287315  0.000000
6   4.190000e+09  721.222717        Ice  40.788548  0.000000
7   4.180000e+09  680.434169        Ice  43.991142  0.000000
8   4.170000e+09  636.443027        Ice  53.817410  0.000000
9   4.160000e+09  582.625617        Ice  22.966430  0.000000
10  4.150000e+09  559.659187        Ice  32.864044  0.000000
11  4.140000e+09  526.795143        Ice  41.121887  0.000000
12  4.130000e+09  485.673256        Ice  17.636642  0.000000
13  4.120000e+09  468.036614        Ice  35.520405  0.000000
14  4.110000e+09  432.516209        Ice  29.316853  0.000000
15  4.100000e+09  403.199356  Shoemaker  16.653557  2.997679
16  4.090000e+09  383.548119        Ice   6.263685  0.000000
17  4.080000e+09  377.284434        Ice  14.141494  0.000000
18  4.070000e+09  363.142940        Ice  48.046450  0.000000